import json, os

arb_dir = r"C:\_IridoApp_October\ai_eye_capture_oct\lib\l10n"

new_keys = {
    # simple_gated_camera.dart - validation error messages
    "errorImageShape": {
        "en": "Image shape incorrect - ensure eye fills frame",
        "es": "Forma de imagen incorrecta - asegúrese de que el ojo llene el marco",
        "pt": "Forma da imagem incorreta - garanta que o olho preencha o quadro",
        "pt_BR": "Forma da imagem incorreta - garanta que o olho preencha o quadro",
        "fr": "Forme de l'image incorrecte - assurez-vous que l'œil remplit le cadre",
        "de": "Bildform falsch - stellen Sie sicher, dass das Auge den Rahmen füllt",
        "it": "Forma dell'immagine errata - assicurarsi che l'occhio riempia il frame",
        "ja": "画像形状が不正 - 目がフレームを満たすようにしてください",
        "ko": "이미지 형태 오류 - 눈이 프레임을 채우도록 하세요",
    },
    "errorNoEyeDetected": {
        "en": "No eye detected - center iris in frame",
        "es": "No se detectó ojo - centre el iris en el marco",
        "pt": "Nenhum olho detectado - centralize a íris no quadro",
        "pt_BR": "Nenhum olho detectado - centralize a íris no quadro",
        "fr": "Aucun œil détecté - centrez l'iris dans le cadre",
        "de": "Kein Auge erkannt - Iris in der Mitte des Rahmens positionieren",
        "it": "Nessun occhio rilevato - centrare l'iride nel frame",
        "ja": "目が検出されません - フレーム内で虹彩を中央に合わせてください",
        "ko": "눈이 감지되지 않음 - 프레임 중앙에 홍채를 위치시키세요",
    },
    "errorNoPupilDetected": {
        "en": "No pupil detected - ensure good lighting",
        "es": "No se detectó pupila - asegure buena iluminación",
        "pt": "Nenhuma pupila detectada - garanta boa iluminação",
        "pt_BR": "Nenhuma pupila detectada - garanta boa iluminação",
        "fr": "Aucune pupille détectée - assurez un bon éclairage",
        "de": "Keine Pupille erkannt - gute Beleuchtung sicherstellen",
        "it": "Nessuna pupilla rilevata - assicurarsi di avere una buona illuminazione",
        "ja": "瞳孔が検出されません - 適切な照明を確保してください",
        "ko": "동공이 감지되지 않음 - 적절한 조명을 확보하세요",
    },
    "errorNoIrisTexture": {
        "en": "No iris texture - move closer to eye",
        "es": "Sin textura de iris - acérquese más al ojo",
        "pt": "Sem textura de íris - aproxime-se mais do olho",
        "pt_BR": "Sem textura de íris - aproxime-se mais do olho",
        "fr": "Pas de texture d'iris - rapprochez-vous de l'œil",
        "de": "Keine Iristextur - näher ans Auge heranrücken",
        "it": "Nessuna texture dell'iride - avvicinarsi all'occhio",
        "ja": "虹彩テクスチャなし - 目に近づいてください",
        "ko": "홍채 질감 없음 - 눈에 더 가까이 이동하세요",
    },
    "errorUnusualColors": {
        "en": "Unusual colors detected - avoid screens/reflections",
        "es": "Colores inusuales detectados - evite pantallas/reflejos",
        "pt": "Cores incomuns detectadas - evite telas/reflexos",
        "pt_BR": "Cores incomuns detectadas - evite telas/reflexos",
        "fr": "Couleurs inhabituelles détectées - évitez les écrans/reflets",
        "de": "Ungewöhnliche Farben erkannt - Bildschirme/Reflexionen vermeiden",
        "it": "Colori insoliti rilevati - evitare schermi/riflessi",
        "ja": "異常な色が検出されました - スクリーン/反射を避けてください",
        "ko": "비정상적인 색상 감지 - 화면/반사를 피하세요",
    },
    "errorTooManyEdges": {
        "en": "Too many straight edges - this may not be an eye",
        "es": "Demasiados bordes rectos - esto puede no ser un ojo",
        "pt": "Muitas bordas retas - isto pode não ser um olho",
        "pt_BR": "Muitas bordas retas - isto pode não ser um olho",
        "fr": "Trop de bords droits - ceci n'est peut-être pas un œil",
        "de": "Zu viele gerade Kanten - dies ist möglicherweise kein Auge",
        "it": "Troppi bordi retti - potrebbe non essere un occhio",
        "ja": "直線エッジが多すぎます - これは目ではないかもしれません",
        "ko": "직선 가장자리가 너무 많음 - 눈이 아닐 수 있습니다",
    },
    "errorNotValidEye": {
        "en": "Not a valid eye image - please try again",
        "es": "No es una imagen de ojo válida - por favor intente de nuevo",
        "pt": "Não é uma imagem de olho válida - tente novamente",
        "pt_BR": "Não é uma imagem de olho válida - tente novamente",
        "fr": "Image d'œil non valide - veuillez réessayer",
        "de": "Kein gültiges Augenbild - bitte erneut versuchen",
        "it": "Immagine occhio non valida - riprovare",
        "ja": "有効な目の画像ではありません - もう一度お試しください",
        "ko": "유효한 눈 이미지가 아닙니다 - 다시 시도하세요",
    },
    # simple_gated_camera.dart - check labels
    "checkImageShape": {
        "en": "Image Shape",
        "es": "Forma de la imagen",
        "pt": "Forma da imagem",
        "pt_BR": "Forma da imagem",
        "fr": "Forme de l'image",
        "de": "Bildform",
        "it": "Forma dell'immagine",
        "ja": "画像形状",
        "ko": "이미지 형태",
    },
    "checkCircularIris": {
        "en": "Circular Iris",
        "es": "Iris circular",
        "pt": "Íris circular",
        "pt_BR": "Íris circular",
        "fr": "Iris circulaire",
        "de": "Kreisförmige Iris",
        "it": "Iride circolare",
        "ja": "円形虹彩",
        "ko": "원형 홍채",
    },
    "checkDarkPupil": {
        "en": "Dark Pupil",
        "es": "Pupila oscura",
        "pt": "Pupila escura",
        "pt_BR": "Pupila escura",
        "fr": "Pupille sombre",
        "de": "Dunkle Pupille",
        "it": "Pupilla scura",
        "ja": "暗い瞳孔",
        "ko": "어두운 동공",
    },
    "checkIrisTexture": {
        "en": "Iris Texture",
        "es": "Textura del iris",
        "pt": "Textura da íris",
        "pt_BR": "Textura da íris",
        "fr": "Texture de l'iris",
        "de": "Iristextur",
        "it": "Texture dell'iride",
        "ja": "虹彩テクスチャ",
        "ko": "홍채 질감",
    },
    "checkPupilIrisStructure": {
        "en": "Pupil-Iris Structure",
        "es": "Estructura pupila-iris",
        "pt": "Estrutura pupila-íris",
        "pt_BR": "Estrutura pupila-íris",
        "fr": "Structure pupille-iris",
        "de": "Pupillen-Iris-Struktur",
        "it": "Struttura pupilla-iride",
        "ja": "瞳孔-虹彩構造",
        "ko": "동공-홍채 구조",
    },
    "checkNaturalColors": {
        "en": "Natural Colors",
        "es": "Colores naturales",
        "pt": "Cores naturais",
        "pt_BR": "Cores naturais",
        "fr": "Couleurs naturelles",
        "de": "Natürliche Farben",
        "it": "Colori naturali",
        "ja": "自然な色",
        "ko": "자연 색상",
    },
    "checkEdgePattern": {
        "en": "Edge Pattern",
        "es": "Patrón de bordes",
        "pt": "Padrão de bordas",
        "pt_BR": "Padrão de bordas",
        "fr": "Motif de bords",
        "de": "Kantenmuster",
        "it": "Schema dei bordi",
        "ja": "エッジパターン",
        "ko": "가장자리 패턴",
    },
    # uvc_camera_screen.dart - camera status/error messages
    "cameraConnected": {
        "en": "Camera connected",
        "es": "Cámara conectada",
        "pt": "Câmera conectada",
        "pt_BR": "Câmera conectada",
        "fr": "Caméra connectée",
        "de": "Kamera verbunden",
        "it": "Fotocamera connessa",
        "ja": "カメラ接続済み",
        "ko": "카메라 연결됨",
    },
    "cameraDisconnected": {
        "en": "Camera disconnected",
        "es": "Cámara desconectada",
        "pt": "Câmera desconectada",
        "pt_BR": "Câmera desconectada",
        "fr": "Caméra déconnectée",
        "de": "Kamera getrennt",
        "it": "Fotocamera disconnessa",
        "ja": "カメラ切断",
        "ko": "카메라 연결 해제",
    },
    "cameraPermissionDenied": {
        "en": "Camera permission denied",
        "es": "Permiso de cámara denegado",
        "pt": "Permissão da câmera negada",
        "pt_BR": "Permissão da câmera negada",
        "fr": "Permission de caméra refusée",
        "de": "Kamera-Berechtigung verweigert",
        "it": "Autorizzazione fotocamera negata",
        "ja": "カメラのアクセス許可が拒否されました",
        "ko": "카메라 권한 거부됨",
    },
    "cameraFailedInit": {
        "en": "Failed to initialize camera",
        "es": "Error al inicializar la cámara",
        "pt": "Falha ao inicializar câmera",
        "pt_BR": "Falha ao inicializar câmera",
        "fr": "Échec de l'initialisation de la caméra",
        "de": "Kamera-Initialisierung fehlgeschlagen",
        "it": "Impossibile inizializzare la fotocamera",
        "ja": "カメラの初期化に失敗しました",
        "ko": "카메라 초기화 실패",
    },
    "cameraError": {
        "en": "Camera error occurred",
        "es": "Ocurrió un error de cámara",
        "pt": "Ocorreu um erro de câmera",
        "pt_BR": "Ocorreu um erro de câmera",
        "fr": "Une erreur de caméra s'est produite",
        "de": "Kamerafehler aufgetreten",
        "it": "Si è verificato un errore della fotocamera",
        "ja": "カメラエラーが発生しました",
        "ko": "카메라 오류 발생",
    },
    "cameraInUse": {
        "en": "Camera is in use by another app",
        "es": "La cámara está siendo usada por otra aplicación",
        "pt": "Câmera está sendo usada por outro aplicativo",
        "pt_BR": "Câmera está sendo usada por outro aplicativo",
        "fr": "La caméra est utilisée par une autre application",
        "de": "Kamera wird von einer anderen App verwendet",
        "it": "La fotocamera è in uso da un'altra app",
        "ja": "カメラは別のアプリで使用中です",
        "ko": "카메라가 다른 앱에서 사용 중입니다",
    },
    "cameraFormatNotSupported": {
        "en": "Camera format not supported",
        "es": "Formato de cámara no compatible",
        "pt": "Formato de câmera não suportado",
        "pt_BR": "Formato de câmera não suportado",
        "fr": "Format de caméra non pris en charge",
        "de": "Kameraformat nicht unterstützt",
        "it": "Formato fotocamera non supportato",
        "ja": "カメラのフォーマットがサポートされていません",
        "ko": "카메라 형식이 지원되지 않습니다",
    },
    "capturedImageNotFound": {
        "en": "Captured image file not found",
        "es": "Archivo de imagen capturada no encontrado",
        "pt": "Arquivo de imagem capturada não encontrado",
        "pt_BR": "Arquivo de imagem capturada não encontrado",
        "fr": "Fichier image capturé introuvable",
        "de": "Aufgenommene Bilddatei nicht gefunden",
        "it": "File immagine acquisita non trovato",
        "ja": "撮影した画像ファイルが見つかりません",
        "ko": "촬영된 이미지 파일을 찾을 수 없습니다",
    },
    "failedToCaptureImage": {
        "en": "Failed to capture image",
        "es": "Error al capturar imagen",
        "pt": "Falha ao capturar imagem",
        "pt_BR": "Falha ao capturar imagem",
        "fr": "Échec de la capture d'image",
        "de": "Bildaufnahme fehlgeschlagen",
        "it": "Impossibile acquisire l'immagine",
        "ja": "画像の撮影に失敗しました",
        "ko": "이미지 캡처 실패",
    },
    # analysis_screen.dart - quality grades
    "gradeA": {
        "en": "A", "es": "A", "pt": "A", "pt_BR": "A",
        "fr": "A", "de": "A", "it": "A", "ja": "A", "ko": "A",
    },
    "gradeB": {
        "en": "B", "es": "B", "pt": "B", "pt_BR": "B",
        "fr": "B", "de": "B", "it": "B", "ja": "B", "ko": "B",
    },
    "gradeC": {
        "en": "C", "es": "C", "pt": "C", "pt_BR": "C",
        "fr": "C", "de": "C", "it": "C", "ja": "C", "ko": "C",
    },
    "gradeD": {
        "en": "D", "es": "D", "pt": "D", "pt_BR": "D",
        "fr": "D", "de": "D", "it": "D", "ja": "D", "ko": "D",
    },
}

lang_to_file = {
    "en": "app_en.arb", "es": "app_es.arb", "pt": "app_pt.arb",
    "pt_BR": "app_pt_BR.arb", "fr": "app_fr.arb", "de": "app_de.arb",
    "it": "app_it.arb", "ja": "app_ja.arb", "ko": "app_ko.arb",
}

for lang, filename in lang_to_file.items():
    filepath = os.path.join(arb_dir, filename)
    with open(filepath, "r", encoding="utf-8") as f:
        data = json.load(f)
    added = sum(1 for k in new_keys if k not in data)
    for key, translations in new_keys.items():
        if key not in data:
            data[key] = translations[lang]
    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
        f.write("\n")
    print(f"{filename}: +{added}")
print("Done.")
