// lib/services/secure_strings.dart
// Encrypted String Storage - Protects sensitive strings from static analysis
//
// USAGE:
// 1. Run the encoder script (below) to encrypt your strings at build time
// 2. Store encrypted bytes in this file
// 3. Call SecureStrings.revenueCatKey (etc.) at runtime to decrypt

import 'dart:convert';
import 'package:crypto/crypto.dart';


/// Secure string vault with runtime decryption
class SecureStrings {
  // Prevent instantiation
  SecureStrings._();

  // ============================================================
  // ENCRYPTED STRINGS (generated by encoder script)
  // ============================================================

  // RevenueCat API Key - ENCRYPTED
  // Original: "goog************************Wuym"
  static const List<int> _revenueCatKeyEnc = [
    0x4A, 0x41, 0x40, 0x57, 0x6E, 0x7D, 0x46, 0x51, 0x7A, 0x72,
    0x56, 0x48, 0x5F, 0x68, 0x59, 0x45, 0x68, 0x72, 0x49, 0x34,
    0x0C, 0x32, 0x10, 0x25, 0x14, 0x33, 0x03, 0x04, 0x1E, 0x3F,
    0x32, 0x21,
  ];

  // Model asset path - ENCRYPTED
  // Original: "asse*****************onnx"
  static const List<int> _modelPathEnc = [
    0x4C, 0x5D, 0x5C, 0x55, 0x45, 0x41, 0x1C, 0x59, 0x59, 0x19,
    0x54, 0x56, 0x4B, 0x53, 0x64, 0x51, 0x52, 0x5A, 0x5A, 0x2C,
    0x6F, 0x2D, 0x2D, 0x2A, 0x3D,
  ];

  // Add more encrypted strings here as needed...
  // static const List<int> _apiEndpointEnc = [...];

  // ============================================================
  // DECRYPTION KEYS (derived at runtime)
  // ============================================================

  /// Primary obfuscation key - derived from app constants
  static int get _primaryKey {
    // Derive from multiple sources to make it harder to find
    const seed1 = 0x43; // 'C'
    const seed2 = 0x4E; // 'N'
    const seed3 = 0x52; // 'R'
    const seed4 = 0x49; // 'I'
    return (seed1 ^ seed2 ^ seed3 ^ seed4) + 0x17;
  }

  /// Secondary key derived from runtime values
  static int get _secondaryKey {
    final tz = DateTime.now().timeZoneName.hashCode;
    return (tz % 256) ^ 0x5A;
  }

  // ============================================================
  // PUBLIC ACCESSORS (call these to get decrypted strings)
  // ============================================================

  /// Get decrypted RevenueCat API key
  static String get revenueCatKey {
    return _decrypt(_revenueCatKeyEnc, _primaryKey);
  }

  /// Get decrypted model path
  static String get modelPath {
    return _decrypt(_modelPathEnc, _primaryKey);
  }

  // Add more accessors as needed...
  // static String get apiEndpoint => _decrypt(_apiEndpointEnc, _primaryKey);

  // ============================================================
  // DECRYPTION ENGINE
  // ============================================================

  /// Simple XOR decryption with key rotation
  static String _decrypt(List<int> encrypted, int baseKey) {
    final decrypted = <int>[];
    for (var i = 0; i < encrypted.length; i++) {
      // Rotate key based on position for added complexity
      final rotatedKey = (baseKey + i) % 256;
      decrypted.add(encrypted[i] ^ rotatedKey);
    }
    return String.fromCharCodes(decrypted);
  }

  /// AES-like decryption for highly sensitive strings
  static String _decryptAes(List<int> encrypted, String passphrase) {
    // Derive key from passphrase
    final keyBytes = sha256.convert(utf8.encode(passphrase)).bytes;
    final decrypted = <int>[];

    for (var i = 0; i < encrypted.length; i++) {
      final keyByte = keyBytes[i % keyBytes.length];
      decrypted.add(encrypted[i] ^ keyByte);
    }
    return String.fromCharCodes(decrypted);
  }

  // ============================================================
  // SECURE MEMORY HANDLING
  // ============================================================

  /// Cache for frequently accessed strings (cleared periodically)
  static final Map<String, _CachedString> _cache = {};
  static const Duration _cacheLifetime = Duration(minutes: 5);

  /// Get string with caching (reduces repeated decryption)
  static String getCached(String key, String Function() decryptor) {
    final cached = _cache[key];
    if (cached != null && !cached.isExpired) {
      return cached.value;
    }

    final value = decryptor();
    _cache[key] = _CachedString(value, DateTime.now());

    // Cleanup old entries
    _cache.removeWhere((_, v) => v.isExpired);

    return value;
  }

  /// Clear all cached strings (call on logout or security events)
  static void clearCache() {
    _cache.clear();
  }
}

/// Cached string with expiration
class _CachedString {
  final String value;
  final DateTime cachedAt;

  _CachedString(this.value, this.cachedAt);

  bool get isExpired =>
      DateTime.now().difference(cachedAt) > SecureStrings._cacheLifetime;
}

// ============================================================
// STRING ENCODER (Run this offline to encrypt your strings)
// ============================================================

/// Utility class to encrypt strings at build time
/// Run this in a separate script, NOT in the app!
class StringEncoder {
  /// Encode a string for embedding in source code
  static String encodeForSource(String plaintext, int baseKey) {
    final encrypted = <int>[];
    for (var i = 0; i < plaintext.length; i++) {
      final rotatedKey = (baseKey + i) % 256;
      encrypted.add(plaintext.codeUnitAt(i) ^ rotatedKey);
    }

    // Format as Dart list literal
    final hexBytes = encrypted.map((b) => '0x${b.toRadixString(16).padLeft(2, '0').toUpperCase()}').toList();

    // Pretty print with line breaks
    final buffer = StringBuffer('[\n');
    for (var i = 0; i < hexBytes.length; i += 10) {
      final end = (i + 10 < hexBytes.length) ? i + 10 : hexBytes.length;
      buffer.write('    ${hexBytes.sublist(i, end).join(', ')}');
      if (end < hexBytes.length) buffer.write(',');
      buffer.write('\n');
    }
    buffer.write('  ]');

    return buffer.toString();
  }

  /// Print encoding instructions
  static void printEncodingHelp() {
    print('''
╔══════════════════════════════════════════════════════════════╗
║              STRING ENCODER FOR CNRI EYE CAPTURE             ║
╠══════════════════════════════════════════════════════════════╣
║ Run this in a SEPARATE Dart script, not in the app!          ║
║                                                              ║
║ Example usage:                                               ║
║   dart run tool/encode_strings.dart                          ║
║                                                              ║
║ The output goes into secure_strings.dart                     ║
╚══════════════════════════════════════════════════════════════╝
''');
  }
}